{
    'name': 'WooCommerce Connector',
    'version': '18.0.1.0.0',
    'category': 'Sales',
    'summary': 'Conector bidireccional WooCommerce ↔ Odoo',
    'description': 'Sincroniza productos, variantes, stock, precios, pedidos y clientes entre WooCommerce y Odoo en tiempo real.',
    'author': 'Rodogaby1985',
    'website': 'https://github.com/Rodogaby1985/woocommerce_connector',
    'license': 'LGPL-3',
    'depends': ['sale_management', 'stock', 'contacts', 'product'],
    'data': [
        'security/wc_security.xml',
        'security/ir.model.access.csv',
        'data/cron_data.xml',
        'data/queue_data.xml',
        'data/wc_data.xml',
        'views/menu.xml',
        'views/wc_backend_views.xml',
        'views/product_template_views.xml',
        'views/product_product_views.xml',
        'views/sale_order_views.xml',
        'views/res_partner_views.xml',
        'views/wc_queue_job_views.xml',
        'views/wc_dashboard_views.xml',
        'wizards/wc_initial_sync.xml',
        'wizards/wc_price_update.xml',
    ],
    'external_dependencies': {
        'python': ['requests'],
    },
    'installable': True,
    'application': True,
    'auto_install': False,
}
