from . import wc_backend
from . import wc_queue_job
from . import wc_webhook_log
from . import product_attribute
from . import product_template
from . import product_product
from . import res_partner
from . import sale_order
from . import stock_picking
from . import product_category_sync
